# Backend Dockerfile

# Stage 1: Build the application
FROM gradle:8.11.0-alpine AS build
WORKDIR /app

# Copy Gradle Wrapper and build files


COPY build.gradle.kts /app/

COPY src /app/src


# Make Gradle Wrapper executable and build the application

RUN gradle bootJar

# Stage 2: Run the application
FROM openjdk:21-jdk-slim AS runtime
WORKDIR /app

# Copy the built JAR from the build stage
COPY --from=build /app/build/libs/*.jar /app/myapp.jar

EXPOSE 8080
# Run the application
CMD ["java", "-jar", "/app/myapp.jar"]
