
FROM node:23-alpine

# Set working directory
WORKDIR /app

COPY . .


RUN npm install --legacy-peer-deps

# Copy the rest of the application code


# Expose the port the app runs on
EXPOSE 3000



# Start the development server
CMD ["npm", "run", "dev"]
